name: release-assets

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            build_command: build:linux
          - os: macos-latest
            platform: mac
            build_command: build:mac
          - os: windows-latest
            platform: win
            build_command: build:win
    env:
      VITE_GITEE_APP_TOKEN: ${{ secrets.VITE_GITEE_APP_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.26.1 --activate

      - name: Install Dependencies
        run: pnpm install

      - name: Build ${{ matrix.platform }}
        run: pnpm ${{ matrix.build_command }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: |
            desktop/dist-release/*.exe
            desktop/dist-release/*.zip
            desktop/dist-release/*.dmg
            desktop/dist-release/*.AppImage
            desktop/dist-release/*.deb
            desktop/dist-release/*.rpm
            desktop/dist-release/*.tar.gz

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          files: |
            desktop/dist-release/*.exe
            desktop/dist-release/*.zip
            desktop/dist-release/*.dmg
            desktop/dist-release/*.AppImage
            desktop/dist-release/*.snap
            desktop/dist-release/*.deb
            desktop/dist-release/*.rpm
            desktop/dist-release/*.tar.gz
            desktop/dist-release/*.blockmap
            desktop/dist-release/latest*.yml
