name: release-assets

on:
  workflow_dispatch:
  push:
    tags:
      - 'workspace-v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            build_command: build:linux
          - os: macos-latest
            platform: mac
            build_command: build:mac
          - os: windows-latest
            platform: win
            build_command: build:win
    env:
      VITE_GITEE_APP_TOKEN: ${{ secrets.VITE_GITEE_APP_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.26.1 --activate

      - name: Install Dependencies
        run: pnpm install

      - name: Build ${{ matrix.platform }}
        run: pnpm ${{ matrix.build_command }}